from enum import StrEnum


class TradingAction(StrEnum):
    """Strategic action emitted by the trading agent."""

    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class ExecutionMode(StrEnum):
    """Execution modes currently allowed by the application."""

    PAPER = "PAPER"


class MarketType(StrEnum):
    """Explicit venue product family carried through the canonical pipeline."""

    SPOT = "SPOT"
    PERPETUAL = "PERPETUAL"
    FUTURE = "FUTURE"


class DerivativeContractKind(StrEnum):
    """Pricing/P&L family for derivatives instruments."""

    LINEAR = "LINEAR"
    INVERSE = "INVERSE"


class PositionSide(StrEnum):
    """Net direction of one derivative position."""

    LONG = "LONG"
    SHORT = "SHORT"


class MarginMode(StrEnum):
    """Margin isolation mode represented by the PAPER portfolio."""

    ISOLATED = "ISOLATED"
    CROSS = "CROSS"


class RiskDecision(StrEnum):
    """Deterministic Risk Engine outcome."""

    ALLOW = "ALLOW"
    MODIFY = "MODIFY"
    REJECT = "REJECT"


class RiskLimit(StrEnum):
    """Stable identifiers for deterministic checks actually evaluated by Risk."""

    CANONICAL_SYMBOL = "CANONICAL_SYMBOL"
    MARKET_SYMBOL = "MARKET_SYMBOL"
    MARKET_TYPE = "MARKET_TYPE"
    PAIR_WHITELIST = "PAIR_WHITELIST"
    MARKET_CHRONOLOGY = "MARKET_CHRONOLOGY"
    PORTFOLIO_CHRONOLOGY = "PORTFOLIO_CHRONOLOGY"
    MARKET_FRESHNESS = "MARKET_FRESHNESS"
    MAX_ORDER_NOTIONAL = "MAX_ORDER_NOTIONAL"
    ASSET_ROLES = "ASSET_ROLES"
    QUOTE_BALANCE = "QUOTE_BALANCE"
    BUY_CASH = "BUY_CASH"
    SELL_POSITION = "SELL_POSITION"
    DERIVATIVE_CONTRACT = "DERIVATIVE_CONTRACT"
    DERIVATIVE_ORDER_SIZE = "DERIVATIVE_ORDER_SIZE"
    DERIVATIVE_LEVERAGE = "DERIVATIVE_LEVERAGE"
    DERIVATIVE_MARGIN = "DERIVATIVE_MARGIN"
    DERIVATIVE_POSITION_NOTIONAL = "DERIVATIVE_POSITION_NOTIONAL"
    DERIVATIVE_TOTAL_EXPOSURE = "DERIVATIVE_TOTAL_EXPOSURE"
    DERIVATIVE_LIQUIDATION_BUFFER = "DERIVATIVE_LIQUIDATION_BUFFER"
    DERIVATIVE_REVERSAL = "DERIVATIVE_REVERSAL"


class RiskReason(StrEnum):
    """Stable machine-readable reason codes emitted by the Risk Engine."""

    HOLD_NO_EXECUTION = "HOLD_NO_EXECUTION"
    INVALID_SYMBOL = "INVALID_SYMBOL"
    MARKET_SYMBOL_MISMATCH = "MARKET_SYMBOL_MISMATCH"
    MARKET_TYPE_MISMATCH = "MARKET_TYPE_MISMATCH"
    PAIR_NOT_ALLOWED = "PAIR_NOT_ALLOWED"
    FUTURE_MARKET_STATE = "FUTURE_MARKET_STATE"
    FUTURE_PORTFOLIO_STATE = "FUTURE_PORTFOLIO_STATE"
    MARKET_FRESHNESS_UNAVAILABLE = "MARKET_FRESHNESS_UNAVAILABLE"
    MARKET_DATA_STALE = "MARKET_DATA_STALE"
    ASSET_ROLE_CONFLICT = "ASSET_ROLE_CONFLICT"
    QUOTE_BALANCE_MISSING = "QUOTE_BALANCE_MISSING"
    POSITION_NOT_HELD = "POSITION_NOT_HELD"
    INSUFFICIENT_POSITION = "INSUFFICIENT_POSITION"
    SELL_AVAILABLE_LIMIT = "SELL_AVAILABLE_LIMIT"
    INSUFFICIENT_CASH = "INSUFFICIENT_CASH"
    BUY_CASH_LIMIT = "BUY_CASH_LIMIT"
    MAX_ORDER_NOTIONAL_EXCEEDED = "MAX_ORDER_NOTIONAL_EXCEEDED"
    MAX_ORDER_NOTIONAL_LIMIT = "MAX_ORDER_NOTIONAL_LIMIT"
    NO_EXECUTABLE_QUANTITY = "NO_EXECUTABLE_QUANTITY"
    DERIVATIVE_CONTEXT_MISSING = "DERIVATIVE_CONTEXT_MISSING"
    DERIVATIVE_CONTRACT_UNSUPPORTED = "DERIVATIVE_CONTRACT_UNSUPPORTED"
    DERIVATIVE_MIN_ORDER_QUANTITY = "DERIVATIVE_MIN_ORDER_QUANTITY"
    DERIVATIVE_POSITION_SIZE_EXCEEDED = "DERIVATIVE_POSITION_SIZE_EXCEEDED"
    DERIVATIVE_CROSS_MARGIN_UNSUPPORTED = "DERIVATIVE_CROSS_MARGIN_UNSUPPORTED"
    DERIVATIVE_LEVERAGE_EXCEEDED = "DERIVATIVE_LEVERAGE_EXCEEDED"
    DERIVATIVE_MARGIN_INSUFFICIENT = "DERIVATIVE_MARGIN_INSUFFICIENT"
    DERIVATIVE_MARGIN_LIMIT = "DERIVATIVE_MARGIN_LIMIT"
    DERIVATIVE_POSITION_NOTIONAL_EXCEEDED = "DERIVATIVE_POSITION_NOTIONAL_EXCEEDED"
    DERIVATIVE_TOTAL_EXPOSURE_EXCEEDED = "DERIVATIVE_TOTAL_EXPOSURE_EXCEEDED"
    DERIVATIVE_LIQUIDATION_RISK = "DERIVATIVE_LIQUIDATION_RISK"
    DERIVATIVE_ACCIDENTAL_REVERSAL = "DERIVATIVE_ACCIDENTAL_REVERSAL"
    DERIVATIVE_REDUCE_ONLY_LIMIT = "DERIVATIVE_REDUCE_ONLY_LIMIT"


class LLMModel(StrEnum):
    """LLM selections supported by configuration."""

    LUNA = "gpt-5.6-luna"
    SOL = "gpt-5.6-sol"


class ExperimentVariable(StrEnum):
    """Single controlled variable intentionally changed inside an experiment group."""

    LLM_MODEL = "LLM_MODEL"
