from enum import StrEnum


class TradingAction(StrEnum):
    """Strategic action emitted by the trading agent."""

    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class ExecutionMode(StrEnum):
    """Execution modes currently allowed by the application."""

    PAPER = "PAPER"


class RiskDecision(StrEnum):
    """Deterministic Risk Engine outcome."""

    ALLOW = "ALLOW"
    MODIFY = "MODIFY"
    REJECT = "REJECT"


class RiskLimit(StrEnum):
    """Stable identifiers for deterministic checks actually evaluated by Risk."""

    CANONICAL_SYMBOL = "CANONICAL_SYMBOL"
    MARKET_SYMBOL = "MARKET_SYMBOL"
    PAIR_WHITELIST = "PAIR_WHITELIST"
    MARKET_CHRONOLOGY = "MARKET_CHRONOLOGY"
    PORTFOLIO_CHRONOLOGY = "PORTFOLIO_CHRONOLOGY"
    MARKET_FRESHNESS = "MARKET_FRESHNESS"
    MAX_ORDER_NOTIONAL = "MAX_ORDER_NOTIONAL"
    ASSET_ROLES = "ASSET_ROLES"
    QUOTE_BALANCE = "QUOTE_BALANCE"
    BUY_CASH = "BUY_CASH"
    SELL_POSITION = "SELL_POSITION"


class RiskReason(StrEnum):
    """Stable machine-readable reason codes emitted by the Risk Engine."""

    HOLD_NO_EXECUTION = "HOLD_NO_EXECUTION"
    INVALID_SYMBOL = "INVALID_SYMBOL"
    MARKET_SYMBOL_MISMATCH = "MARKET_SYMBOL_MISMATCH"
    PAIR_NOT_ALLOWED = "PAIR_NOT_ALLOWED"
    FUTURE_MARKET_STATE = "FUTURE_MARKET_STATE"
    FUTURE_PORTFOLIO_STATE = "FUTURE_PORTFOLIO_STATE"
    MARKET_FRESHNESS_UNAVAILABLE = "MARKET_FRESHNESS_UNAVAILABLE"
    MARKET_DATA_STALE = "MARKET_DATA_STALE"
    ASSET_ROLE_CONFLICT = "ASSET_ROLE_CONFLICT"
    QUOTE_BALANCE_MISSING = "QUOTE_BALANCE_MISSING"
    POSITION_NOT_HELD = "POSITION_NOT_HELD"
    INSUFFICIENT_POSITION = "INSUFFICIENT_POSITION"
    SELL_AVAILABLE_LIMIT = "SELL_AVAILABLE_LIMIT"
    INSUFFICIENT_CASH = "INSUFFICIENT_CASH"
    BUY_CASH_LIMIT = "BUY_CASH_LIMIT"
    MAX_ORDER_NOTIONAL_EXCEEDED = "MAX_ORDER_NOTIONAL_EXCEEDED"
    MAX_ORDER_NOTIONAL_LIMIT = "MAX_ORDER_NOTIONAL_LIMIT"
    NO_EXECUTABLE_QUANTITY = "NO_EXECUTABLE_QUANTITY"


class LLMModel(StrEnum):
    """LLM selections supported by configuration."""

    LUNA = "gpt-5.6-luna"
    SOL = "gpt-5.6-sol"
